### ISSUE TITLE
About Page Customization

### ISSUE THREAD

**Issue by LeCoupa** [TelescopeJS/CrunchHunt#1]
Hello,

I've implemented a system to edit the about page directly from the administration by following your code base. Would you be interested about a pull request?

**Comment by SachaG** [comment]
Yes, that would be very cool! But maybe you could think about submitting a PR to Telescope instead, or else writing a tutorial about it? CrunchHunt is just a one-time side project so I'm not really working on it.

**Comment by LeCoupa** [comment]
Yes I can do that Sacha. I'm building something for the next few days. I'll submit a PR to telescope next week. And by the way, I love your Dribbble :-)

**Comment by SachaG** [comment]
Awesome :) I'm afraid my Dribbble account has been a little neglected lately… Blame Telescope!

**Comment by queso** [comment]
Surely CrunchHunt and GridScope could be on Dribbble? :D

**Comment by SachaG** [comment]
They don't look very nice…
